[tool.poetry]
name = "mqtt-to-eventhub"
version = "0.1.0"
description = ""
authors = ["rob al <mnbf9rca@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "mqtt_to_eventhub"}]

[tool.poetry.dependencies]
python = "^3.9"
paho-mqtt = "^1.6.1"
python-dotenv-vault = "^0.4.1"
azure-eventhub = "^5.11.1"
asyncio-mqtt = "^0.16.1"
requests = "^2.28.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
pytest-asyncio = "^0.21.1"
flake8 = "6.0.0"
black = "22.12.0"
pre-commit = "2.21.0"
types-paho-mqtt = "1.6.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
